project_id = "zppcobirzgpfcrnxznwe"

[functions.create-team-member]
verify_jwt = false

[functions.get-team-members]
verify_jwt = false

[functions.manage-team-member]
verify_jwt = false

[functions.submit-lead]
verify_jwt = false

[functions.update-lead]
verify_jwt = false
