project_id = "zppcobirzgpfcrnxznwe"

[functions.create-team-member]
verify_jwt = false

[functions.get-team-members]
verify_jwt = false

[functions.manage-team-member]
verify_jwt = false

[functions.submit-lead]
verify_jwt = false

[functions.update-lead]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.check-reminders]
verify_jwt = false

[functions.store-api]
verify_jwt = false

[functions.send-proposal-email]
verify_jwt = false
